SCIENCEOPEN_DATABASE_NAME = "ScienceOpen"
EMERALD_DATABASE_NAME = "Emerald"
CORE_DATABASE_NAME = "CORE"
ARXIV_DATABASE_NAME = "arXiv"

ABSTRACT_DICTIONARY_KEY = "abstract"
PUBLISHED_DATE_DICTIONARY_KEY = "published_date"
SOURCE_DICTIONARY_KEY = "source"